### ISSUE TITLE
상세 페이지 UI

### ISSUE THREAD

**Issue by jeffoio** [ios-study-boost/Hazzle-iOS#18]
- 퍼즐 이미지 
- 현재 연속 달성 일수
- 역대 연속 달성 일수
- 메모? (달력으로 날짜 변경 기능 필요)

**Comment by jwonyLee** [comment]
![image](https://user-images.githubusercontent.com/15073405/97673711-8fea9500-1acf-11eb-833a-324e4696702e.png)
